### ISSUE TITLE
New update breaks Thermionic Fabricator Recipes

### ISSUE THREAD

**Issue by al132** [jaredlll08/ModTweaker#393]
Something in the new modtweaker version seems to have broken my Thermionic Fabricator recipes

From my minetweaker log:
https://gist.github.com/al132/bf83044e2f03fb4dc244e5a54139dc84

**Comment by jaredlll08** [comment]
Do me a favor, upload your jar file to like Dropbox or something please

**Comment by al132** [comment]
https://drive.google.com/drive/folders/0B1khLdydIhhNT25SblFBcFFyMFk

**Comment by davqvist** [comment]
Can confirm, I just tested the new update, both adding a recipe to the Thermionic Fabricator and the Carpenter results in a java.lang.NoClassDefFoundError: modtweaker/mods/forestry/recipes/DescriptiveRecipe.
If you need more info let me know.

**Comment by jaredlll08** [comment]
Fixed in dev

**Comment by davqvist** [comment]
Don't get me wrong, but when do you plan to push another update so that I can test if it works now?

**Comment by jaredlll08** [comment]
When I do it.

**Comment by davqvist** [comment]
The update I just installed didn't fix the Thermionic Fabricator issue. I still get exactly the same error message al132 posted.
